const LRU = require('lru-cache');

module.exports.cache = new LRU({
  max: 300,
  allowStale: true,
  ttl: 60 * 60 * 1000,
});

module.exports.CACHE_PRESET_KEYS = {
  LAST_RAID_MEMBERS: 'LAST_RAID_MEMBERS',
  CLAN_MEMBERS: 'CLAN_MEMBERS',
  ADMIN_ACCESS_MEMBERS: 'ADMIN_ACCESS_MEMBERS',
  MEMBERS_WITH_LAST_RAID_ATTACKS_AND_EXTRA_DATA: 'MEMBERS_WITH_LAST_RAID_ATTACKS_AND_EXTRA_DATA',
  MEMBERS_EXTRA_DATA: 'MEMBERS_EXTRA_DATA',
  PROMOTIONS_REQUIREMENTS: 'PROMOTIONS_REQUIREMENTS',
};
